// fangyu-flow/src/components/TopToolbar.tsx
import React, { useState, useRef, useEffect } from 'react'
import { demoFlows } from '../utils/demoFlows'

const CATEGORY_ORDER = ['流程控制', 'AI 能力', '数据操作', '记忆存储', '工具集成', '其他']

const DEMO_CATEGORY_BY_ID: Record<string, string> = {
  core: 'AI 能力',
  condition: '流程控制',
  switch: '流程控制',
  loop: '流程控制',
  approval: '流程控制',
  knowledge: 'AI 能力',
  search_web: '工具集成',
  memory: '记忆存储',
  ext: '工具集成',
  text_processing: '数据操作',
  variable: '数据操作',
  mcp: '工具集成',
  tool_call: '工具集成',
  tool_skill: '工具集成',
  trigger: '流程控制',
  code_exec: 'AI 能力',
  var_text: '数据操作',
  memory_extract: '记忆存储',
  prompt: 'AI 能力',
  role: 'AI 能力',
  actionWorker: 'AI 能力',
}

function inferCategory(id: string): string {
  return demoFlows[id].category || DEMO_CATEGORY_BY_ID[id] || '其他'
}

const GROUPED_DEMOS = CATEGORY_ORDER.map(cat => ({
  category: cat,
  items: Object.keys(demoFlows)
    .filter(id => inferCategory(id) === cat)
    .map(id => ({
      id,
      label: demoFlows[id].label,
      desc: demoFlows[id].desc || '',
    })),
})).filter(g => g.items.length > 0)

const DEMO_COUNT = Object.keys(demoFlows).length

interface Props {
  onNewFlow: () => void
  onSaveFlow: () => void
  onShowHistory: () => void
  onImportFlow: () => void
  onExportFlow: () => void
  onOpenFlowConfig: () => void
  onGroupSelected: () => void
  onUngroupSelected: () => void
  onDeleteSelected: () => void
  onSimulate: () => void
  onBatchTest: () => void
  onFileSelected: (e: React.ChangeEvent<HTMLInputElement>) => void
  onOpenSettings: () => void
  onLoadDemo: (demoId: string) => void
  simulating?: boolean
}

export default function TopToolbar(props: Props) {
  const Btn = ({ title, onClick, primary, children }: { title?: string; onClick: () => void; primary?: boolean; children: React.ReactNode }) => (
    <button className={`notion-btn${primary ? ' primary' : ''}`} onClick={onClick} title={title}>
      {children}
    </button>
  )

  return (
    <div style={{
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      height: 'var(--header-height)', padding: '0 12px',
      borderBottom: '1px solid var(--border-color)', background: 'var(--bg-primary)',
      userSelect: 'none', flexShrink: 0,
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 100 }}>
        <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)', letterSpacing: '-0.3px' }}>fangyu</span>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
        <Btn onClick={props.onNewFlow} title="新建画布">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
          新建
        </Btn>
        <Btn onClick={props.onSaveFlow} primary title="保存 Ctrl+S">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>
          保存
        </Btn>
        <Btn onClick={props.onShowHistory} title="保存历史">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
          历史
        </Btn>
        <Btn onClick={props.onImportFlow} title="导入流程JSON">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
          导入
        </Btn>
        <Btn onClick={props.onExportFlow} title="导出（源码 + 配置 + 可执行文件）">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
          导出
        </Btn>
        <DemoMenu groups={GROUPED_DEMOS} count={DEMO_COUNT} onSelect={props.onLoadDemo} />
        <div style={{ width: 1, height: 20, background: 'var(--border-color)', margin: '0 4px' }} />
        <Btn onClick={props.onGroupSelected} title="封装为组合原子">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>
          组合
        </Btn>
        <Btn onClick={props.onUngroupSelected} title="展开组合原子">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="9" y1="12" x2="15" y2="12"/><line x1="12" y1="9" x2="12" y2="15"/></svg>
          展开
        </Btn>
        <div style={{ width: 1, height: 20, background: 'var(--border-color)', margin: '0 4px' }} />
        <Btn onClick={props.onDeleteSelected} title="删除选中 Delete">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><line x1="10" y1="11" x2="10" y2="17"/><line x1="14" y1="11" x2="14" y2="17"/></svg>
          删除
        </Btn>
        <Btn onClick={props.onOpenFlowConfig} title="画布配置">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 20V10"/><path d="M18 20V4"/><path d="M6 20v-4"/></svg>
          提示词
        </Btn>
        <Btn onClick={props.onSimulate} primary title="模拟运行" style={props.simulating ? { opacity: 0.6, pointerEvents: 'none' } : undefined}>
          {props.simulating ? (
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ animation: 'spin 0.8s linear infinite' }}>
              <circle cx="12" cy="12" r="10" strokeDasharray="30 70"/>
            </svg>
          ) : (
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>
          )}
          {props.simulating ? '运行中...' : '模拟运行'}
        </Btn>
        <Btn onClick={props.onBatchTest} title="批量测试">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>
          批量测试
        </Btn>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 100, justifyContent: 'flex-end' }}>
        <Btn onClick={props.onOpenSettings} title="设置">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>
        </Btn>
        <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>v1.0</span>
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )
}

function DemoMenu({ groups, count, onSelect }: {
  groups: { category: string; items: { id: string; label: string; desc: string }[] }[]
  count: number
  onSelect: (id: string) => void
}) {
  const [open, setOpen] = useState(false)
  const [pos, setPos] = useState({ top: 0, left: 0 })
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!open) return
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [open])

  return (
    <div ref={ref} style={{ position: 'relative', display: 'inline-block' }}>
      <button className="notion-btn" onClick={(e) => {
        const r = e.currentTarget.getBoundingClientRect()
        setPos({ top: r.bottom + 4, left: r.left })
        setOpen(o => !o)
      }} title={`加载示例流程 (${count} 个)`}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/>
        </svg>
        用例 ({count})
      </button>
      {open && (
        <div style={{
          position: 'fixed', top: pos.top, left: pos.left, zIndex: 10000, background: '#fff', borderRadius: 8,
          boxShadow: '0 4px 20px rgba(0,0,0,0.15)', border: '1px solid #eee',
          minWidth: 260, maxHeight: '75vh', overflowY: 'auto',
        }}>
          {groups.map(g => (
            <div key={g.category}>
              <div style={{ padding: '8px 12px 4px', fontSize: 10, fontWeight: 700, color: '#9b9a97', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                {g.category} ({g.items.length})
              </div>
              {g.items.map(d => (
                <button key={d.id} style={{
                  display: 'block', width: '100%', textAlign: 'left', padding: '8px 12px 8px 16px',
                  border: 'none', background: 'transparent', cursor: 'pointer', fontSize: 12,
                  borderBottom: '1px solid #f5f5f3',
                }}
                  onClick={() => { onSelect(d.id); setOpen(false) }}
                  onMouseEnter={e => e.currentTarget.style.background = '#f5f5f3'}
                  onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                >
                  <div style={{ fontWeight: 600, color: '#37352f', marginBottom: 2 }}>{d.label}</div>
                  <div style={{ fontSize: 11, color: '#9b9a97' }}>{d.desc}</div>
                </button>
              ))}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// frontend/src/components/TopToolbar.vue
<template>
  <div class="top-toolbar">
    <div class="toolbar-left">
      <span class="toolbar-brand">fangyu</span>
    </div>
    <div class="toolbar-center">
      <button class="notion-btn" @click="$emit('new-flow')" title="新建画布">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
        新建
      </button>
      <button class="notion-btn primary" @click="$emit('save-flow')" title="保存 Ctrl+S">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>
        保存
      </button>
      <button class="notion-btn" @click="$emit('show-history')" title="保存历史">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
        历史
      </button>
      <button class="notion-btn" @click="$emit('import-flow')" title="导入流程JSON">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
        导入
      </button>
      <button class="notion-btn" @click="$emit('export-flow')" title="导出流程JSON">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>
        导出
      </button>
      <div class="toolbar-divider"></div>
      <button class="notion-btn" @click="$emit('group-selected')" title="封装为组合原子">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>
        组合
      </button>
      <button class="notion-btn" @click="$emit('ungroup-selected')" title="展开组合原子">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="9" y1="12" x2="15" y2="12"/><line x1="12" y1="9" x2="12" y2="15"/></svg>
        展开
      </button>
      <div class="toolbar-divider"></div>
      <button class="notion-btn primary" @click="$emit('simulate')" title="模拟运行">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>
        模拟运行
      </button>
    </div>
    <div class="toolbar-right">
      <button class="notion-btn toolbar-icon-btn" @click="$emit('open-settings')" title="设置">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>
      </button>
      <span class="toolbar-hint">v1.0</span>
    </div>
    <input ref="fileInput" type="file" accept=".json" style="display:none" @change="$emit('file-selected', $event)">
  </div>
</template>

<script setup>
import { ref } from 'vue'

const fileInput = ref(null)

defineEmits(['new-flow', 'save-flow', 'import-flow', 'export-flow', 'group-selected', 'ungroup-selected', 'simulate', 'file-selected', 'show-history', 'open-settings'])

function triggerFileInput() {
  fileInput.value?.click()
}

defineExpose({ triggerFileInput })
</script>

<style scoped>
.top-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: var(--header-height);
  padding: 0 12px;
  border-bottom: 1px solid var(--border-color);
  background: var(--bg-primary);
  user-select: none;
  flex-shrink: 0;
}
.toolbar-left {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 100px;
}
.toolbar-brand {
  font-size: 14px;
  font-weight: 700;
  color: var(--text-primary);
  letter-spacing: -0.3px;
}
.toolbar-center {
  display: flex;
  align-items: center;
  gap: 4px;
}
.toolbar-right {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 100px;
  justify-content: flex-end;
}
.toolbar-hint {
  font-size: 11px;
  color: var(--text-muted);
}
.toolbar-divider {
  width: 1px;
  height: 20px;
  background: var(--border-color);
  margin: 0 4px;
}
</style>
