// frontend/src/components/ChatInterface.vue
<template>
  <div class="chat-interface" :class="{ expanded: expanded }">
    <div class="chat-bar" @click="expanded = !expanded">
      <div class="chat-bar-left">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
        <span>运行预览</span>
      </div>
      <div class="chat-bar-right">
        <span v-if="messages.length > 0" class="chat-msg-count">{{ messages.length }} 条消息</span>
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" :style="{ transform: expanded ? 'rotate(180deg)' : '' }"><polyline points="6 9 12 15 18 9"/></svg>
      </div>
    </div>

    <div v-if="expanded" class="chat-body">
      <div class="chat-messages" ref="msgListRef">
        <div v-if="messages.length === 0" class="chat-empty">
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#bfbeba" stroke-width="1.5"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
          <span class="chat-empty-text">在下方输入消息，运行当前流程</span>
        </div>
        <div v-for="(msg, i) in messages" :key="i" class="chat-msg" :class="'msg-' + msg.role">
          <div class="msg-avatar">
            <svg v-if="msg.role === 'user'" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
            <svg v-else width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
          </div>
          <div class="msg-content">
            <div class="msg-name">{{ msg.role === 'user' ? '你' : 'AI' }}</div>
            <div class="msg-text" v-html="renderMarkdown(msg.content)"></div>
            <div v-if="msg.logs && msg.logs.length > 0" class="msg-logs">
              <div class="msg-logs-toggle" @click="msg._showLogs = !msg._showLogs">
                <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="6 9 12 15 18 9"/></svg>
                执行日志 ({{ msg.logs.length }})
              </div>
              <div v-if="msg._showLogs" class="msg-logs-body">
                <div v-for="(log, li) in msg.logs" :key="li" class="log-line" :class="'log-' + log.type">
                  <span class="log-icon">{{ log.type === 'start' ? '▶' : log.type === 'complete' ? '✓' : '✗' }}</span>
                  <span class="log-node">{{ log.nodeName }}</span>
                  <span class="log-info">
                    <template v-if="log.type === 'start'">输入: {{ truncate(log.data.inputs, 60) }}</template>
                    <template v-else-if="log.type === 'complete'">输出: {{ truncate(log.data.outputs, 60) }}</template>
                    <template v-else>{{ log.data.error }}</template>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div v-if="running" class="chat-msg msg-assistant">
          <div class="msg-avatar">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
          </div>
          <div class="msg-content">
            <div class="msg-name">AI</div>
            <div class="msg-text typing">
              <span class="typing-dot"></span>
              <span class="typing-dot"></span>
              <span class="typing-dot"></span>
            </div>
          </div>
        </div>
      </div>

      <div class="chat-input-area">
        <div class="chat-input-row">
          <input
            ref="inputRef"
            class="chat-input"
            v-model="inputText"
            placeholder="输入消息，按 Enter 发送..."
            @keydown.enter.prevent="sendMessage"
            :disabled="running"
          />
          <button class="chat-send-btn" :disabled="running || !inputText.trim()" @click="sendMessage">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, nextTick, watch } from 'vue'
import { Executor } from '../utils/executor'

const props = defineProps({ lf: { type: Object, default: null } })

const expanded = ref(true)
const inputText = ref('')
const messages = ref([])
const running = ref(false)
const msgListRef = ref(null)
const inputRef = ref(null)

watch(expanded, () => { nextTick(() => scrollToBottom()) })

function scrollToBottom() {
  nextTick(() => {
    if (msgListRef.value) {
      msgListRef.value.scrollTop = msgListRef.value.scrollHeight
    }
  })
}

async function sendMessage() {
  const text = inputText.value.trim()
  if (!text || running.value || !props.lf) return
  inputText.value = ''
  running.value = true

  messages.value.push({
    role: 'user',
    content: text,
    _showLogs: false,
  })
  scrollToBottom()

  const executor = new Executor(props.lf)
  executor.setExternalInputs({ query: text })
  executor.setGlobalVars({ _chatHistory: buildChatHistory() })

  try {
    const result = await executor.run()
    const logs = executor.getLogs()

    const lastLLM = result.results?.find(r => r.type === 'llm' && r.outputs?.result)
    const output = lastLLM?.outputs?.result || ''

    messages.value.push({
      role: 'assistant',
      content: output || '(流程执行完成，无输出)',
      logs,
      _showLogs: logs.length > 0,
    })
  } catch (err) {
    messages.value.push({
      role: 'assistant',
      content: `执行出错: ${err.message}`,
      logs: [],
      _showLogs: false,
    })
  }

  running.value = false
  scrollToBottom()
}

function buildChatHistory() {
  const history = []
  const msgs = messages.value
  for (let i = Math.max(0, msgs.length - 10); i < msgs.length; i++) {
    const m = msgs[i]
    if (m.role === 'user') history.push({ role: 'user', content: m.content })
    else if (m.role === 'assistant' && m.content) history.push({ role: 'assistant', content: m.content })
  }
  return history
}

function truncate(val, len) {
  if (!val) return '—'
  const s = typeof val === 'string' ? val : JSON.stringify(val)
  return s.length > len ? s.slice(0, len) + '…' : s
}

function renderMarkdown(text) {
  if (!text) return ''
  let html = escapeHtml(text)
  html = html.replace(/\n/g, '<br>')
  html = html.replace(/```(\w*)\n?([\s\S]*?)```/g, (_, lang, code) => {
    return `<pre><code>${escapeHtml(code)}</code></pre>`
  })
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>')
  html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  html = html.replace(/\*([^*]+)\*/g, '<em>$1</em>')
  return html
}

function escapeHtml(str) {
  const div = document.createElement('div')
  div.textContent = str
  return div.innerHTML
}
</script>

<style scoped>
.chat-interface {
  border-top: 1px solid var(--border-color);
  background: var(--bg-primary);
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
}
.chat-interface.expanded {
  height: 280px;
}
.chat-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 6px 14px;
  cursor: pointer;
  user-select: none;
  flex-shrink: 0;
  border-bottom: 1px solid var(--border-light);
}
.chat-bar:hover { background: var(--bg-hover); }
.chat-bar-left {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  font-weight: 600;
  color: var(--text-primary);
}
.chat-bar-right {
  display: flex;
  align-items: center;
  gap: 8px;
}
.chat-msg-count {
  font-size: 11px;
  color: var(--text-muted);
}
.chat-body {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 8px 12px;
}
.chat-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  height: 100%;
  min-height: 80px;
}
.chat-empty-text {
  font-size: 12px;
  color: var(--text-muted);
}
.chat-msg {
  display: flex;
  gap: 8px;
  margin-bottom: 12px;
}
.msg-avatar {
  width: 28px;
  height: 28px;
  border-radius: 6px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.msg-user .msg-avatar { background: #e8e8e6; color: #37352f; }
.msg-assistant .msg-avatar { background: #37352f; color: #fff; }
.msg-content {
  flex: 1;
  min-width: 0;
}
.msg-name {
  font-size: 11px;
  font-weight: 600;
  color: var(--text-secondary);
  margin-bottom: 2px;
}
.msg-text {
  font-size: 13px;
  line-height: 1.6;
  color: var(--text-primary);
  word-break: break-word;
  white-space: pre-wrap;
}
.msg-text :deep(pre) {
  background: #f5f5f3;
  border: 1px solid var(--border-color);
  border-radius: 6px;
  padding: 8px 12px;
  overflow-x: auto;
  font-size: 11px;
  line-height: 1.5;
  margin: 6px 0;
}
.msg-text :deep(code) {
  background: #f0f0ee;
  padding: 1px 4px;
  border-radius: 3px;
  font-size: 12px;
}
.msg-text :deep(pre code) {
  background: none;
  padding: 0;
}
.typing {
  display: flex;
  gap: 3px;
  align-items: center;
  padding: 4px 0;
}
.typing-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--text-muted);
  animation: typingBounce 1.4s infinite ease-in-out both;
}
.typing-dot:nth-child(1) { animation-delay: -0.32s; }
.typing-dot:nth-child(2) { animation-delay: -0.16s; }
.typing-dot:nth-child(3) { animation-delay: 0s; }
@keyframes typingBounce {
  0%, 80%, 100% { transform: scale(0); }
  40% { transform: scale(1); }
}
.msg-logs { margin-top: 6px; }
.msg-logs-toggle {
  font-size: 11px;
  color: var(--text-muted);
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 4px;
}
.msg-logs-toggle:hover { color: var(--text-primary); }
.msg-logs-body {
  margin-top: 4px;
  background: #fafaf8;
  border: 1px solid var(--border-light);
  border-radius: 6px;
  padding: 6px 8px;
  max-height: 120px;
  overflow-y: auto;
  font-size: 10px;
  font-family: 'Cascadia Code', 'Consolas', monospace;
}
.log-line {
  display: flex;
  gap: 4px;
  padding: 2px 0;
  align-items: flex-start;
}
.log-icon { flex-shrink: 0; font-weight: 700; }
.log-start .log-icon { color: #1890ff; }
.log-complete .log-icon { color: #52c41a; }
.log-error .log-icon { color: #ff4d4f; }
.log-node {
  font-weight: 600;
  color: var(--text-primary);
  flex-shrink: 0;
  white-space: nowrap;
}
.log-info {
  color: var(--text-muted);
  word-break: break-all;
}
.chat-input-area {
  padding: 8px 12px;
  border-top: 1px solid var(--border-light);
  flex-shrink: 0;
}
.chat-input-row {
  display: flex;
  gap: 6px;
}
.chat-input {
  flex: 1;
  padding: 8px 12px;
  border: 1px solid var(--border-color);
  border-radius: var(--radius-md);
  font-size: 13px;
  outline: none;
  background: var(--bg-secondary);
  color: var(--text-primary);
}
.chat-input:focus { border-color: var(--text-primary); }
.chat-input:disabled { opacity: 0.5; }
.chat-send-btn {
  width: 36px;
  height: 36px;
  border: none;
  border-radius: var(--radius-md);
  background: #37352f;
  color: #fff;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  transition: background 0.15s;
}
.chat-send-btn:hover { background: #2b2a26; }
.chat-send-btn:disabled { background: #d0d0ce; cursor: not-allowed; }
</style>

// fangyu-canvas/src/components/ChatInterface.tsx
import { useCallback, useRef, useState, useEffect } from 'react'
import { getReactFlowInstance } from './FlowCanvas'
import { Executor } from '../utils/executor'
import type { ExecutorLog } from '../utils/executor'
import { convertToExportFormat } from '../utils/flowHelper'
import { useAppSelector } from '../store/hooks'
import { deployAllAgents } from '../utils/externalAgent'
import {
  buildPipelineFromCanvas,
  hasCollaborationPipeline,
  orchestrateAgents,
  type CollabStepResult,
} from '../utils/agentOrchestrate'
import { ViolationPanel, formatViolationSummary, type ViolationPayload } from './ViolationPanel'
import { warningsToViolationPayload } from '../utils/constitutionWarnings'


interface ChatMessage {
  role: string
  content: string
  logs?: ExecutorLog[]
  _showLogs?: boolean
  _pendingSkill?: string
  _pendingSkillDesc?: string
  _collabSteps?: CollabStepResult[]
  _showCollab?: boolean
  _violation?: ViolationPayload
  _showViolation?: boolean
}

const STORAGE_KEY = 'ai-flow-chat-messages'

function loadMessages(): ChatMessage[] {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]') } catch { return [] }
}

interface ChatInterfaceProps { headerless?: boolean }

export default function ChatInterface({ headerless }: ChatInterfaceProps) {
  const [expanded, setExpanded] = useState(true)
  const [inputText, setInputText] = useState('')
  const [messages, setMessages] = useState<ChatMessage[]>(loadMessages)
  const [running, setRunning] = useState(false)
  const [chatMode, setChatMode] = useState<'flow' | 'agent'>('flow')
  const [agentCollabMode, setAgentCollabMode] = useState(true)
  const [selectedSkill, setSelectedSkill] = useState('')
  const msgListRef = useRef<HTMLDivElement>(null)
  const agentNodes = useAppSelector(s => s.agent.nodes)
  const [selectedAgent, setSelectedAgent] = useState('')

  useEffect(() => {
    const onChatMode = (e: Event) => {
      const mode = (e as CustomEvent).detail?.mode
      if (mode === 'agent' || mode === 'flow') setChatMode(mode)
    }
    window.addEventListener('fangyu:switch-chat-mode', onChatMode)
    return () => window.removeEventListener('fangyu:switch-chat-mode', onChatMode)
  }, [])

  const collabPipeline = buildPipelineFromCanvas(agentNodes)
  const canCollab = hasCollaborationPipeline(agentNodes)

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(messages))
  }, [messages])

  const agents = agentNodes.filter(n => n.type === 'a2a-agent' || n.type === 'a2a-external')

  const scrollToBottom = useCallback(() => {
    setTimeout(() => {
      if (msgListRef.current) msgListRef.current.scrollTop = msgListRef.current.scrollHeight
    }, 50)
  }, [])

  const sendToAgent = useCallback(async (text: string) => {
    try {
      await deployAllAgents(agentNodes)

      if (agentCollabMode && collabPipeline && collabPipeline.length >= 2) {
        const result = await orchestrateAgents(text, collabPipeline, 'append')
        if (!result.success) {
          setMessages(prev => [...prev, {
            role: 'assistant',
            content: result.violation ? formatViolationSummary(result.violation) : (result.error || '协作执行失败'),
            _collabSteps: result.steps,
            _showCollab: true,
            _violation: result.violation,
            _showViolation: !!result.violation,
          }])
          return
        }
        setMessages(prev => [...prev, {
          role: 'assistant',
          content: result.final_output || '(无输出)',
          _collabSteps: result.steps,
          _showCollab: true,
        }])
        return
      }

      const target = selectedAgent || agents[0]?.id
      if (!target) {
        setMessages(prev => [...prev, { role: 'assistant', content: '请先在 Agent 画布添加 Agent 节点' }])
        return
      }
      const agent = agents.find(a => a.id === target)
      const skillId = selectedSkill || agent?.agentCard?.skills?.[0]?.id || 'default'
      const resp = await fetch('/api/v1/a2a/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          target_agent: target,
          message: {
            role: 'user',
            parts: [{ type: 'text', text }],
            metadata: { skill_id: skillId },
          },
        }),
      })
      const task = await resp.json()
      if (task.violation) {
        setMessages(prev => [...prev, {
          role: 'assistant',
          content: formatViolationSummary(task.violation),
          _violation: task.violation,
          _showViolation: true,
        }])
        return
      }
      const lastAgentMsg = task.history?.filter((m: { role: string }) => m.role === 'agent').pop()
      const output = lastAgentMsg?.parts?.[0]?.text
        || task.output?.results?.slice(-1)?.[0]?.outputs?.result
        || '(无输出)'
      setMessages(prev => [...prev, { role: 'assistant', content: String(output) }])
    } catch {
      setMessages(prev => [...prev, { role: 'assistant', content: 'Agent 通信失败，请确认后端已启动' }])
    }
  }, [selectedAgent, selectedSkill, agents, agentNodes, agentCollabMode, collabPipeline])

  const sendMessage = useCallback(async () => {
    const text = inputText.trim()
    if (!text || running) return
    setInputText('')
    setRunning(true)
    const addMsg = (content: string, extra?: any) => setMessages(prev => [...prev, { role: 'assistant', content, ...(extra || {}) }])

    setMessages(prev => [...prev, { role: 'user', content: text, _showLogs: false }])
    scrollToBottom()

    if (chatMode === 'agent') {
      await sendToAgent(text)
      setRunning(false)
      scrollToBottom()
      return
    }

    if (text.startsWith('/learn ')) {
      const desc = text.slice(7).trim()
      try {
        const resp = await fetch('/api/v1/llm/chat', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            messages: [
              { role: 'system', content: '你是一个技能生成器。根据用户描述，生成一个 Markdown 技能文件。格式：\n```markdown\n# 技能名称\n## 描述\n简短描述\n## 步骤\n1. ...\n2. ...\n```\n只返回技能内容，不要额外解释。' },
              { role: 'user', content: desc },
            ], model: 'deepseek-v4-flash', stream: false,
          }),
        })
        const json = await resp.json()
        addMsg(json.result || '', { _pendingSkill: json.result, _pendingSkillDesc: desc })
      } catch (err) {
        addMsg(`/learn 执行出错: ${err instanceof Error ? err.message : String(err)}`)
      }
      setRunning(false); scrollToBottom(); return
    }

    const instance = getReactFlowInstance()
    if (!instance) { setRunning(false); return }
    const nodes = instance.getNodes(); const edges = instance.getEdges()
    const flowData = convertToExportFormat(nodes, edges)
    const history = messages.slice(-10).map(m => ({ role: m.role, content: m.content }))

    const executor = new Executor(flowData.nodes, flowData.links)
    executor.setExternalInputs({ query: text, message: text })
    executor.setGlobalVars({ _chatHistory: history })

    try {
      const result = await executor.run()
      if (!result.success && result.violation) {
        addMsg(formatViolationSummary(result.violation), {
          _violation: result.violation,
          _showViolation: true,
        })
        setRunning(false)
        scrollToBottom()
        return
      }
      const logs = result.logs || []
      const allOutputs = result.results || []
      const lastLLM = allOutputs.find(r => r.type === 'llm' && r.outputs?.result)
      const lastNonLLM = [...allOutputs].reverse().find(r => !['start', 'end', 'output'].includes(r.type) && r.outputs?.result)
      const output = lastLLM?.outputs?.result as string || lastNonLLM?.outputs?.result as string || ''
      const warnPayload = result.constitution_warnings?.length
        ? warningsToViolationPayload(result.constitution_warnings)
        : undefined

      addMsg(output || '(流程执行完成，无输出)', {
        logs,
        _showLogs: logs.length > 0,
        _violation: warnPayload,
        _showViolation: !!warnPayload,
      })

      fetch('/api/v1/search/index', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role: 'user', content: text }) }).catch(() => {})
      if (output) {
        fetch('/api/v1/search/index', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role: 'assistant', content: output }) }).catch(() => {})
        const extractNodes = allOutputs.filter(r => r.type === 'extract-memory')
        if (extractNodes.length === 0) {
          fetch('/api/v1/memory/extract', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: output, max_facts: 3, scope: 'user' }) }).catch(() => {})
        }
      }
    } catch (err) {
      addMsg(`执行出错: ${err instanceof Error ? err.message : String(err)}`, { logs: [], _showLogs: false })
    }
    setRunning(false)
    scrollToBottom()
  }, [inputText, running, messages, scrollToBottom, chatMode, sendToAgent])

  const content = (
    <>
      <div style={{ display: 'flex', gap: 4, padding: '4px 12px', borderBottom: '1px solid var(--border-light)', flexShrink: 0 }}>
        <button onClick={() => setChatMode('flow')} style={{
          padding: '2px 10px', border: 'none', borderRadius: 4, cursor: 'pointer', fontSize: 11,
          background: chatMode === 'flow' ? '#37352f' : 'transparent', color: chatMode === 'flow' ? '#fff' : '#888',
        }}>Flow 聊天</button>
        <button onClick={() => setChatMode('agent')} style={{
          padding: '2px 10px', border: 'none', borderRadius: 4, cursor: 'pointer', fontSize: 11,
          background: chatMode === 'agent' ? '#722ed1' : 'transparent', color: chatMode === 'agent' ? '#fff' : '#888',
        }} disabled={agents.length === 0}>Agent 聊天</button>
        {chatMode === 'agent' && canCollab && (
          <button onClick={() => setAgentCollabMode(v => !v)} style={{
            padding: '2px 10px', border: 'none', borderRadius: 4, cursor: 'pointer', fontSize: 11,
            background: agentCollabMode ? '#13c2c2' : 'transparent', color: agentCollabMode ? '#fff' : '#888',
          }} title={`链式协作 ${collabPipeline?.length || 0} 步`}>
            {agentCollabMode ? `协作模式 (${collabPipeline?.length})` : '单 Agent'}
          </button>
        )}
        {chatMode === 'agent' && agents.length > 0 && !agentCollabMode && (
          <>
            <select value={selectedAgent || agents[0]?.id || ''} onChange={e => { setSelectedAgent(e.target.value); setSelectedSkill('') }}
              style={{ marginLeft: 4, fontSize: 11, padding: '1px 4px', border: '1px solid #ddd', borderRadius: 4 }}>
              {agents.map(a => <option key={a.id} value={a.id}>{a.label}</option>)}
            </select>
            {(() => {
              const ag = agents.find(a => a.id === (selectedAgent || agents[0]?.id))
              const skills = ag?.agentCard?.skills || []
              if (skills.length <= 1) return null
              return (
                <select value={selectedSkill || skills[0]?.id || ''} onChange={e => setSelectedSkill(e.target.value)}
                  style={{ marginLeft: 4, fontSize: 11, padding: '1px 4px', border: '1px solid #ddd', borderRadius: 4 }}>
                  {skills.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                </select>
              )
            })()}
          </>
        )}
      </div>
      <div ref={msgListRef} style={{ flex: 1, overflowY: 'auto', padding: '8px 12px' }}>
        {messages.length === 0 && (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8, height: '100%', minHeight: 80 }}>
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#bfbeba" strokeWidth="1.5"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
            <span style={{ fontSize: 12, color: '#bfbeba' }}>
              {chatMode === 'flow'
                ? '输入消息运行流程，/learn <描述> 学习技能'
                : agentCollabMode && canCollab
                  ? `协作模式：${collabPipeline?.map(s => s.label).join(' → ') || ''}`
                  : '选择 Agent 并发送消息'}
            </span>
          </div>
        )}
        {messages.map((msg, i) => (
          <div key={i} style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
            <div style={{ width: 28, height: 28, borderRadius: 6, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, background: msg.role === 'user' ? '#e8e8e6' : '#37352f', color: msg.role === 'user' ? '#37352f' : '#fff' }}>
              {msg.role === 'user' ? (
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
              ) : (
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
              )}
            </div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 2 }}>{msg.role === 'user' ? '你' : 'AI'}</div>
              <div style={{ fontSize: 13, lineHeight: 1.6, color: 'var(--text-primary)', wordBreak: 'break-word', whiteSpace: 'pre-wrap' }}>{msg.content}</div>
              <ViolationPanel
                violation={msg._violation}
                expanded={msg._showViolation !== false}
                onToggle={() => setMessages(prev => prev.map((m, idx) => idx === i ? { ...m, _showViolation: !m._showViolation } : m))}
              />
              {msg._collabSteps && msg._collabSteps.length > 0 && (
                <div style={{ marginTop: 8 }}>
                  <div style={{ fontSize: 11, color: '#13c2c2', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4 }}
                    onClick={() => setMessages(prev => prev.map((m, idx) => idx === i ? { ...m, _showCollab: !m._showCollab } : m))}>
                    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="6 9 12 15 18 9"/></svg>
                    协作过程 ({msg._collabSteps.length} 步)
                  </div>
                  {msg._showCollab && (
                    <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 6 }}>
                      {msg._collabSteps.map(step => (
                        <div key={`${step.index}-${step.agent}`} style={{
                          background: '#f0fffe', border: '1px solid #b5f5ec', borderRadius: 6, padding: '8px 10px',
                        }}>
                          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                            <span style={{ fontSize: 11, fontWeight: 700, color: '#08979c' }}>
                              {step.index + 1}. {step.label}
                            </span>
                            <span style={{ fontSize: 10, color: '#888' }}>
                              {step.state}{step.duration_ms ? ` · ${step.duration_ms}ms` : ''}
                            </span>
                          </div>
                          <div style={{ fontSize: 11, color: '#666', marginBottom: 2 }}>技能: {step.skill_id}</div>
                          <div style={{ fontSize: 12, lineHeight: 1.5, color: 'var(--text-primary)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                            {step.output || '(无输出)'}
                          </div>
                          {step.violation && (
                            <ViolationPanel violation={step.violation} expanded />
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
              {msg._pendingSkill && (
                <div style={{ marginTop: 8, display: 'flex', gap: 6 }}>
                  <button style={{ padding: '4px 14px', fontSize: 12, border: 'none', borderRadius: 6, background: '#37352f', color: '#fff', cursor: 'pointer' }}
                    onClick={async () => {
                      try {
                        const saveResp = await fetch('/api/v1/skills/learn-from-llm', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content: msg._pendingSkill }) })
                        const saveJson = await saveResp.json()
                        setMessages(prev => prev.map((m, idx) => idx === i ? { ...m, _pendingSkill: undefined } : m))
                        if ((saveJson.count || 0) > 0) setMessages(prev => [...prev, { role: 'assistant', content: `✅ 已学习 ${saveJson.count} 个技能！`, logs: [], _showLogs: false }])
                      } catch { setMessages(prev => [...prev, { role: 'assistant', content: '❌ 技能保存失败', logs: [], _showLogs: false }]) }
                    }}
                  >✅ 确认保存</button>
                  <button style={{ padding: '4px 14px', fontSize: 12, border: '1px solid var(--border-color)', borderRadius: 6, background: 'transparent', color: 'var(--text-muted)', cursor: 'pointer' }}
                    onClick={() => setMessages(prev => prev.map((m, idx) => idx === i ? { ...m, _pendingSkill: undefined } : m))}>取消</button>
                </div>
              )}
              {msg.logs && msg.logs.length > 0 && (
                <div style={{ marginTop: 6 }}>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4 }}
                    onClick={() => setMessages(prev => prev.map((m, idx) => idx === i ? { ...m, _showLogs: !m._showLogs } : m))}>
                    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="6 9 12 15 18 9"/></svg>
                    执行日志 ({msg.logs.length})
                  </div>
                  {msg._showLogs && (
                    <div style={{ marginTop: 4, background: '#fafaf8', border: '1px solid var(--border-light)', borderRadius: 6, padding: '6px 8px', maxHeight: 120, overflowY: 'auto', fontSize: 10, fontFamily: "'Cascadia Code', 'Consolas', monospace" }}>
                      {msg.logs.map((log, li) => (
                        <div key={li} style={{ display: 'flex', gap: 4, padding: '2px 0', alignItems: 'flex-start' }}>
                          <span style={{ flexShrink: 0, fontWeight: 700, color: log.type === 'start' ? '#1890ff' : log.type === 'complete' ? '#52c41a' : '#ff4d4f' }}>
                            {log.type === 'start' ? '▶' : log.type === 'complete' ? '✓' : '✗'}
                          </span>
                          <span style={{ fontWeight: 600, color: 'var(--text-primary)', flexShrink: 0, whiteSpace: 'nowrap' }}>{log.nodeName}</span>
                          <span style={{ color: 'var(--text-muted)', wordBreak: 'break-all' }}>
                            {log.type === 'start' ? `输入: ${truncate(JSON.stringify(log.data.inputs), 60)}` : log.type === 'complete' ? `输出: ${truncate(JSON.stringify(log.data.outputs), 60)}` : String(log.data.error)}
                          </span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        ))}
        {running && (
          <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
            <div style={{ width: 28, height: 28, borderRadius: 6, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, background: '#37352f', color: '#fff' }}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 2 }}>AI</div>
              <div style={{ display: 'flex', gap: 3, alignItems: 'center', padding: '4px 0' }}>
                <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--text-muted)', animation: 'typingBounce 1.4s infinite ease-in-out both' }} />
                <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--text-muted)', animation: 'typingBounce 1.4s infinite ease-in-out both', animationDelay: '-0.16s' }} />
                <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--text-muted)', animation: 'typingBounce 1.4s infinite ease-in-out both', animationDelay: '0s' }} />
              </div>
            </div>
          </div>
        )}
      </div>

      <div style={{ padding: '8px 12px', borderTop: '1px solid var(--border-light)', flexShrink: 0 }}>
        <div style={{ display: 'flex', gap: 6 }}>
          <input style={{ flex: 1, padding: '8px 12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', fontSize: 13, outline: 'none', background: 'var(--bg-secondary)', color: 'var(--text-primary)' }}
            value={inputText} onChange={e => setInputText(e.target.value)}
            placeholder={chatMode === 'flow' ? '输入消息... (/learn <描述>)' : '向 Agent 发送消息...'}
            onKeyDown={e => e.key === 'Enter' && sendMessage()} disabled={running}
          />
          <button style={{ width: 36, height: 36, border: 'none', borderRadius: 'var(--radius-md)', background: inputText.trim() && !running ? '#37352f' : '#d0d0ce', color: '#fff', cursor: inputText.trim() && !running ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}
            disabled={running || !inputText.trim()} onClick={sendMessage}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
          </button>
        </div>
      </div>
    </>
  )

  if (headerless) return <div style={{ display: 'flex', flexDirection: 'column', height: '100%', background: 'var(--bg-primary)' }}>{content}</div>

  return (
    <div style={{ borderTop: '1px solid var(--border-color)', background: 'var(--bg-primary)', display: 'flex', flexDirection: 'column', flexShrink: 0, height: expanded ? 280 : 'auto' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 14px', cursor: 'pointer', userSelect: 'none', flexShrink: 0, borderBottom: '1px solid var(--border-light)' }}
        onClick={() => setExpanded(!expanded)}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, fontWeight: 600, color: 'var(--text-primary)' }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
          <span>运行预览</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          {messages.length > 0 && <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{messages.length} 条消息</span>}
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ transform: expanded ? 'rotate(180deg)' : undefined }}>
            <polyline points="6 9 12 15 18 9"/>
          </svg>
        </div>
      </div>
      {expanded && content}
    </div>
  )
}

function truncate(val: string, len: number) {
  if (!val) return ''; if (val.length <= len) return val; return val.slice(0, len) + '...'
}
